### Библиотека NumPy

In [84]:
import numpy as np

In [85]:
# скалярнок случайное целое значение
arr_0 = np.random.randint(10)
# 1- мерный массив (вектор-строка) со случайными целыми значениями
arr_0 = np.random.randint(-10,10, size=5)
# 1- мерный массив (вектор-строка) со случайными целыми значениями
arr_0 = np.random.randint(-10,10, size=(4,1))
# 1- мерный массив (вектор-строка) со случайными целыми значениями
arr_0 = np.random.randint(-10,10, size=(4,6))
arr_0

array([[-7, -8, -5,  7,  1,  9],
       [ 1, -2,  1,  7,  0,  1],
       [-4, -9,  1, -3, -3, -5],
       [ 6, -7, -7,  8, -9, -5]])

In [86]:
# 2-мерный массив случайных значений с плаваоющей точкой в диапазоне от 0 до 1
np.random.random((3,4))

array([[0.46694764, 0.27439083, 0.85651045, 0.60528176],
       [0.6539014 , 0.47924769, 0.77818361, 0.76309432],
       [0.66461746, 0.40065356, 0.51691802, 0.8808118 ]])

In [87]:
# 2-мерный массив случайных значений с плавающей точкой 
# из нормального (гауссова распрелеоения)
np.random.normal(size=(4,4))

array([[-0.32680052,  0.38361712, -0.43821162,  0.31174327],
       [-2.21464986,  1.18095297,  0.00746287,  1.4803389 ],
       [ 0.22109467,  0.11254413,  0.56971906, -0.84405194],
       [ 0.03778475,  0.43819199,  1.3430074 , -0.45354476]])

In [88]:
# Атрибуты

# форма массива
arr_0.shape

(4, 6)

In [89]:
# тип данных 
arr_0.dtype

dtype('int32')

In [90]:
# мерность массива
arr_0.ndim

2

In [91]:
# объем занимаемой памяти (в байтах)
arr_0.nbytes

96

In [92]:
# количество всех элементов массива
arr_0.size

24

In [93]:
# методы

# конвертация типа данных
arr_0.astype('int16')

array([[-7, -8, -5,  7,  1,  9],
       [ 1, -2,  1,  7,  0,  1],
       [-4, -9,  1, -3, -3, -5],
       [ 6, -7, -7,  8, -9, -5]], dtype=int16)

In [94]:
# транспонирование - поворот массива по диагонали
#arr_0.transpose()
arr_0.T

array([[-7,  1, -4,  6],
       [-8, -2, -9, -7],
       [-5,  1,  1, -7],
       [ 7,  7, -3,  8],
       [ 1,  0, -3, -9],
       [ 9,  1, -5, -5]])

In [95]:
# минимальное значение
arr_0.min(axis=1)

array([-8, -2, -9, -9])

In [96]:
# максимальное значение
arr_0.max(axis=1)

array([9, 7, 1, 8])

In [97]:
# среднее значение
arr_0.mean()

-1.3333333333333333

In [98]:
# сортировка массива
arr_0.sort(axis=0)

In [99]:
arr_0

array([[-7, -9, -7, -3, -9, -5],
       [-4, -8, -5,  7, -3, -5],
       [ 1, -7,  1,  7,  0,  1],
       [ 6, -2,  1,  8,  1,  9]])

In [100]:
arr_0[::-1, :]

array([[ 6, -2,  1,  8,  1,  9],
       [ 1, -7,  1,  7,  0,  1],
       [-4, -8, -5,  7, -3, -5],
       [-7, -9, -7, -3, -9, -5]])

In [101]:
# Индексация

arr_1 = np.random.randint(10, size=10)
arr_1

array([1, 0, 6, 6, 6, 9, 7, 4, 0, 5])

In [102]:
# прямая индексация
arr_1[0]

1

In [103]:
# обратная индексация
arr_1[-1]

5

In [104]:
arr_2 = np.random.randint(10, size=(4,5))
arr_2

array([[2, 2, 6, 0, 8],
       [7, 0, 7, 7, 0],
       [9, 3, 4, 6, 1],
       [7, 6, 1, 9, 9]])

In [105]:
arr_2[1]

array([7, 0, 7, 7, 0])

In [106]:
arr_2[:, -1]

array([8, 0, 1, 9])

In [107]:
arr_2[2,1]

3

In [108]:
arr_2

array([[2, 2, 6, 0, 8],
       [7, 0, 7, 7, 0],
       [9, 3, 4, 6, 1],
       [7, 6, 1, 9, 9]])

In [110]:
# срезы

# срез по строкам
arr_2[1:3]

array([[7, 0, 7, 7, 0],
       [9, 3, 4, 6, 1]])

In [111]:
# срез по столбцам
arr_2[:, :3]

array([[2, 2, 6],
       [7, 0, 7],
       [9, 3, 4],
       [7, 6, 1]])

In [112]:
# срез по строкам и по столбцам
arr_2[2:,:3]

array([[9, 3, 4],
       [7, 6, 1]])